language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t shellyygtw/docker-kubernetes-practice -f Dockerfile.dev .

script:
  - docker run shellyygtw/docker-kubernetes-practice npm run test -- --coverage